// <auto-generated />
namespace ConsoleApplication3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relacionamentonn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relacionamentonn));
        
        string IMigrationMetadata.Id
        {
            get { return "201611070144161_relacionamento-n-n"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
